name: "Phanalist"
description: "Performant static analyzer for PHP, which is extremely easy to use. It helps you catch common mistakes in your PHP code."
author: Denzyl Dick
branding:
  icon: alert-triangle
  color: purple
inputs:
  src:
    description: "Path to project sources."
    required: true
    default: ".src/"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Download phanalist.
      shell: bash
      run: curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/denzyldick/phanalist/main/bin/init.sh | sh
    - name: Display version
      shell: bash
      run: /home/runner/phanalist --help
    - name: Running phanalist
      continue-on-error: true
      shell: bash
      run: /home/runner/phanalist --src=${GITHUB_WORKSPACE}${INPUT_SRC} --output-format=sarif | tee result.sarif
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ GITHUB_WORKSPACE }}/results.sarif
